# Generated by Django 3.2.5 on 2021-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulo",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
