# Generated by Django 3.2.5 on 2021-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulos", "0003_populando_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulo",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="order",
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="publico",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="slug",
            field=models.SlugField(),
        ),
    ]
