# Generated by Django 3.2.5 on 2021-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperitivos", "0002_video_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(max_length=32),
        ),
    ]
